# .github/workflows/ci.yml
name: Go CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    # Set default working directory for subsequent run steps
    # because go.mod is in the ticketron subdirectory.
    defaults:
      run:
        working-directory: .
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23.8' # Use Go version from go.mod

    - name: Build
      # Runs 'make build' in the ./ticketron directory due to defaults
      run: make build

    - name: Test
      # Runs 'make test' in the ./ticketron directory due to defaults
      run: make test

    - name: Run Integration Tests
      # Runs 'make test-integration' in the ./ticketron directory due to defaults
      run: make test-integration

    - name: Run Lint
      # Runs 'make lint' in the ./ticketron directory due to defaults
      run: make lint

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: karolswdev/ticketron

    - name: Run govulncheck
      # Runs 'make vulncheck' in the ./ticketron directory due to defaults
      run: make vulncheck