# .github/workflows/ci.yml
name: Go CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    # Set default working directory for subsequent run steps
    # because go.mod is in the ticketron subdirectory.
    defaults:
      run:
        working-directory: ./ticketron
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23.8' # Use Go version from go.mod

    - name: Build
      # Runs 'make build' in the ./ticketron directory due to defaults
      run: make build

    - name: Test
      # Runs 'make test' in the ./ticketron directory due to defaults
      run: make test

    - name: Run Integration Tests
      # Runs 'make test-integration' in the ./ticketron directory due to defaults
      run: make test-integration

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      # No token needed here if CODECOV_TOKEN secret is set in GitHub repo settings


    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v4
      with:
        # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
        version: latest
        # Optional: working directory, useful for monorepos
        # working-directory: somedir # Not needed due to job defaults
        # Optional: golangci-lint command line arguments.
        # args: --issues-exit-code=0 # Initially allow issues
        # Optional: show only new issues if it's a pull request. The default value is `false`.
        # only-new-issues: true

    - name: Run govulncheck
      # Runs 'make vulncheck' in the ./ticketron directory due to defaults
      run: make vulncheck