name: Release Ticketron

on:
  push:
    tags:
      - 'v*' # Trigger on version tags like v1.0.0

permissions:
  contents: write # Needed to create GitHub releases

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for version info

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22' # Specify your Go version

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          # Optional: set the version of GoReleaser to use. Defaults to latest
          # version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Optional: If you need to pass other secrets or variables
          # YOUR_SECRET: ${{ secrets.YOUR_SECRET }}